import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    title: {
      fontSize: 32,
      fontWeight: 'bold',
      marginBottom: 20,
      color: '#f5f3ff',
      fontFamily: 'System',
      letterSpacing: 0.7,
    },
     searchBar: {
        height: 50,
        borderWidth: 1,
        borderColor: 'rgba(103, 232, 249, 0.35)',
        borderRadius: 14,
        paddingHorizontal: 20,
        marginBottom: 20,
        fontSize: 16,
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
        color: '#f5f3ff',
        fontFamily: 'System',
    },
    userList: {
        flex: 1,
        marginBottom: 20,
    },
    userCard: {
        backgroundColor: 'rgba(30, 27, 75, 0.72)',
        padding: 15,
        borderRadius: 12,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: 'rgba(103, 232, 249, 0.25)',
        shadowColor: '#22d3ee',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    },
    userHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#f5f3ff',
        marginBottom: 5,
    },
    userId: {
        fontSize: 14,
        color: '#a5b4fc',
        marginBottom: 3,
    },
    userLogin: {
        fontSize: 14,
        color: '#a5b4fc',
    },
    taskSummary: {
        marginTop: 10,
        paddingTop: 10,
        borderTopWidth: 1,
        borderTopColor: 'rgba(103, 232, 249, 0.18)',
    },
    taskCount: {
        fontSize: 14,
        fontWeight: '600',
        color: '#67e8f9',
    },
    expandHint: {
        fontSize: 12,
        color: '#a5b4fc',
        marginTop: 5,
        fontStyle: 'italic',
    },
    expandIcon: {
        fontSize: 20,
        color: '#67e8f9',
        padding: 10,
        fontWeight: 'bold',
    },
    tasksContainer: {
        marginTop: 15,
        paddingTop: 15,
        borderTopWidth: 1,
        borderTopColor: 'rgba(103, 232, 249, 0.18)',
    },
    tasksTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#c4b5fd',
        marginBottom: 10,
    },
    taskCard: {
        backgroundColor: 'rgba(76, 29, 149, 0.35)',
        padding: 12,
        borderRadius: 10,
        marginBottom: 10,
        borderLeftWidth: 4,
        borderLeftColor: '#22d3ee',
    },
    taskHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 8,
    },
    taskName: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#f5f3ff',
        flex: 1,
    },
    taskStatus: {
        fontSize: 11,
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        color: '#fff',
        fontWeight: 'bold',
        overflow: 'hidden',
    },
    taskDetail: {
        fontSize: 13,
        color: '#c4b5fd',
        marginTop: 4,
    },
    noTasks: {
        textAlign: 'center',
        color: '#a5b4fc',
        fontStyle: 'italic',
        paddingVertical: 10,
    },
    emptyText: {
        textAlign: 'center',
        fontSize: 16,
        color: '#a5b4fc',
        marginTop: 50,
    }
});
